apiVersion: apps/v1
kind: Deployment
metadata:
  name: #{deploymentname}#
  namespace: #{deploymentnamespace}#
spec:
  progressDeadlineSeconds: 3600
  selector:
    matchLabels:
      app: #{deploymentname}#
  replicas: 1
  template:
    
    metadata:
      labels:
        app: #{deploymentname}#
    spec:
      containers:
      - name: #{deploymentname}#
        image: #{acrUrl}#/#{imageRepository}#:#{tag}#
        resources:
          requests:
            memory: #{memoryrequest}#
            
          limits:
            memory: #{memorylimit}#
     
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 443
        envFrom:
       
        - secretRef:
            name: #{deploymentname}#
---

apiVersion: v1
kind: Service
metadata:
 name: ar-web-service
 namespace: #{deploymentnamespace}#
spec:
 type: ClusterIP
 selector:
   app: #{deploymentname}#
 ports:
   - name: http
     protocol: TCP
     port: 80
     targetPort: 8080
   - name: https
     protocol: TCP
     port: 443

   

   

