version: '3.8'

services:
  kafka-ui:
    image: docker.redpanda.com/redpandadata/console:latest
    container_name: kafka-ui
    depends_on:
      - kafka-1
    networks:
      - event_net

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    networks:
      - event_net

  kafka-1:
    image: confluentinc/cp-kafka:7.4.0
    hostname: "kafka-1"
    container_name: "kafka-1"
    depends_on:
      - zookeeper
    networks:
      - event_net

  cassandra-1:
    image: "cassandra:latest"
    container_name: "cassandra-1"
    hostname: "cassandra-1"
    networks:
      - event_net
    volumes:
      - cassandra-node-1:/var/lib/cassandra:rw
    restart:
      on-failure
    healthcheck:
      test: ["CMD-SHELL", "nodetool status"]
      interval: 2m
      start_period: 2m
      timeout: 10s
      retries: 3

  # load-tester:
  #   image: ${DOCKER_REGISTRY-}loadtester
  #   container_name: "load-tester"
  #   build:
  #     context: ..
  #     dockerfile: load-tester/Dockerfile

  command-service:
    image: ${DOCKER_REGISTRY-}commandserviceapi
    container_name: "command-service"
    build:
      context: ..
      dockerfile: command-service/Dockerfile
    networks:
      - event_net
    depends_on:
      - kafka-1

  # command-service-stream:
  #   image: ${DOCKER_REGISTRY-}commandservicestreamapi
  #   container_name: "command-service-stream"
  #   build:
  #     context: ..
  #     dockerfile: command-service-stream/Dockerfile
  #   networks:
  #     - event_net
  #   depends_on:
  #     - kafka-1

  
  domain-service:
    image: ${DOCKER_REGISTRY-}domainservice
    container_name: "domain-service"
    build:
      context: ..
      dockerfile: domain-service/Dockerfile
    networks:
      - event_net

  prometheus:
    image: prom/prometheus:latest
    container_name: "prometheus"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    depends_on:
      - domain-service
    networks:
      - event_net

  grafana:
    image: grafana/grafana:latest
    container_name: "grafana"
    depends_on:
      - prometheus
    networks:
      - event_net
    volumes:
      - grafana-storage:/var/lib/grafana

  loki:
    image: grafana/loki:2.9.2
    container_name: "loki"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki/loki-config.yaml:/etc/loki/local-config.yaml
    networks:
      - event_net

  tempo:
    image: grafana/tempo:2.4.0
    container_name: "tempo"
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ./tempo/tempo.yaml:/etc/tempo.yaml
      - tempo-data:/tmp/tempo
    networks:
      - event_net


networks:
  event_net:
  
volumes:
  cassandra-node-1:
  grafana-storage:
  loki:
  tempo-data:


