version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx_ssl
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    ports:
      - "8080:80"
      - "8445:8445"
    depends_on:
      - angular-app
    networks:
        vpcbr:

  angular-app:
    build:
      context: ./angular-app
      dockerfile: Dockerfile
    container_name: angular_app
    ports:
      - "8001:80"
    networks:
        vpcbr:
  
  web-api:
    build:
      context: ./WebApi
      dockerfile: Dockerfile
    container_name: web_api
    ports:
      - "7003:8080"
    networks:
        vpcbr:
  # bmm-ui-service:
  #   build: 
  #     context: ./bmm-ui-service
  #     args:
  #       envBuild: lara
  #   container_name: bmm_ui_service
  #   ports:
  #     - "8001:8001"
  #     - "8002:80"
  #   networks:
  #       vpcbr:

  # front-end-qa:
  #   image: 117016671394.dkr.ecr.eu-west-1.amazonaws.com/bmm-ui-service:lara-latest
  #   container_name: front-end-qa
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - ASPNETCORE_URLS=http://+:80
  #   ports:
  #       - 8001:80
  #       - 8002:80
  #   expose:
  #     - 8001
  #   restart: always
  #   networks:
  #       vpcbr:
networks:
    vpcbr:
      driver: bridge