apiVersion: v1
kind: ConfigMap
metadata:
  name: ocelot-settings
data:
  ocelot.json: |-
    {
      "Routes": [
        {
          "DownstreamPathTemplate": "/weatherforecast",
          "DownstreamScheme": "http",
          "DownstreamHostAndPorts": [
            {
              "Host": "ar-infra-api-service",
              "Port": 80
            }
          ],
          "UpstreamPathTemplate": "/weather",
          "UpstreamHttpMethod": [ "GET", "POST", "PUT" ]
        },
        {
          "UpstreamHttpMethod": [ "Get" ],
          "UpstreamPathTemplate": "/{url}",
          "DownstreamPathTemplate": "/{url}",
          "DownstreamScheme": "http",
          "DownstreamHostAndPorts": [
            {
              "Host": "ar-infra-api-service",
              "Port": 80
            }
          ]
        }
      ]
    }
